### ISSUE TITLE
SI FACTOR

### ISSUE THREAD

**Issue by hferreira** [4gra/icalreport#1]
Hello,

Sorry to put this question here but I can't find your e-mail.
How do you came with the SI FACTOR 0.05551 on this project https://github.com/4gra/FreeStyleLibre-NFC-Reader ?

My e-mail is hferreira.80@gmail.com

Thank you.

**Comment by 4gra** [comment]
I'll write a wiki page explaining my working and let you know.  I've also enabled Issues for https://github.com/4gra/FreeStyleLibre-NFC-Reader - thanks for pointing it out.

**Comment by 4gra** [comment]
In fact I've just updated https://github.com/4gra/FreeStyleLibre-NFC-Reader/blob/master/README.md now.

**Comment by 4gra** [comment]
I've opened https://github.com/4gra/FreeStyleLibre-NFC-Reader/issues/1 for further discussion.
